# CREATE TABLE bronze.lark_attendance (
#     user_id STRING,
#     attendance_id STRING,
#     attendance_date DATE,
#     employee STRING,
#     group_name STRING,
#     shift_name STRING,
#     check_in_record_id STRING,
#     check_in_datetime TIMESTAMP,
#     check_in_shift_time TIMESTAMP,
#     check_in_location_name STRING,
#     check_in_is_offsite BOOL,
#     check_in_type STRING,
#     check_in_result STRING,
#     check_in_result_supplement STRING,
#     check_out_record_id STRING,
#     check_out_datetime TIMESTAMP,
#     check_out_shift_time TIMESTAMP,
#     check_out_location_name STRING,
#     check_out_is_offsite BOOL,
#     check_out_type STRING,
#     check_out_result STRING,
#     check_out_result_supplement STRING,
#     employee_type STRING,
#     request_penalty BOOL,
#     early_late BOOL,
#     early_late_20_min BOOL,
#     early_late_penalty_price INT64,
#     penalty_early_late_20_min INT64,
#     penalty INT64,
#     reason STRING,
#     etl_inserted TIMESTAMP,
#     partition_value DATE
# ) PARTITION BY partition_value;

TBL_ATTENDANCE = {
    'User id': 'string',
    'Result id': 'string',
    'Date': 'datetime64[ns, UTC]',
    'Employee': 'string',
    'Group name': 'string',
    'Shift name': 'string',
    'Check in record id': 'string',
    'Check in time': 'datetime64[ns, UTC]',
    'Check in shift time': 'datetime64[ns, UTC]',
    'Check in location name': 'string',
    'Check in - Is offsite': 'bool',
    'Check in type': 'string',
    'Check in result': 'string',
    'Check in result supplement': 'string',
    'Check out record id': 'string',
    'Check out time': 'datetime64[ns, UTC]',
    'Check out shift time': 'datetime64[ns, UTC]',
    'Check out location name': 'string',
    'Check out - Is offsite': 'bool',
    'Check out type': 'string',
    'Check out result': 'string',
    'Check out result supplement': 'string',
    'Employee type': 'string',
    'Nhân sự không đồng ý phiếu phạt': 'bool',
    'Đi muộn / về sớm': 'bool',
    'Muộn 20p/sớm 20p': 'bool',
    'Giá phạt đi muộn/ về sớm': 'int64',
    'Phạt muộn 20p/sớm 20p': 'int64',
    'Tiền phạt': 'int64',
    'Lý do': 'string'
}

RENAME_ATTENDANCE_COLS = {
    'User id': 'user_id',
    'Result id': 'attendance_id',
    'Date': 'attendance_date',
    'Employee': 'employee',
    'Group name': 'group_name',
    'Shift name': 'shift_name',
    'Check in record id': 'check_in_record_id',
    'Check in time': 'check_in_datetime',
    'Check in shift time': 'check_in_shift_time',
    'Check in location name': 'check_in_location_name',
    'Check in - Is offsite': 'check_in_is_offsite',
    'Check in type': 'check_in_type',
    'Check in result': 'check_in_result',
    'Check in result supplement': 'check_in_result_supplement',
    'Check out record id': 'check_out_record_id',
    'Check out time': 'check_out_datetime',
    'Check out shift time': 'check_out_shift_time',
    'Check out location name': 'check_out_location_name',
    'Check out - Is offsite': 'check_out_is_offsite',
    'Check out type': 'check_out_type',
    'Check out result': 'check_out_result',
    'Check out result supplement': 'check_out_result_supplement',
    'Employee type': 'employee_type',
    'Nhân sự không đồng ý phiếu phạt': 'request_penalty',
    'Đi muộn / về sớm': 'early_late',
    'Muộn 20p/sớm 20p': 'early_late_20_min',
    'Giá phạt đi muộn/ về sớm': 'early_late_penalty_price',
    'Phạt muộn 20p/sớm 20p': 'penalty_early_late_20_min',
    'Tiền phạt': 'penalty',
    'Lý do': 'reason'
}