# create table silver.fact_payment (
# 	payment_id STRING,
# 	payment_name STRING,
# 	payment_type STRING,
# 	payment_date DATE,
# 	project_name STRING,
# 	goods STRING,
# 	price_unit INT64,
# 	quantity INT64,
# 	price_total INT64,
# 	bill_image STRING,
# 	billing_evidence STRING,
# 	buying_person_name STRING,
#   employee_sur_id STRING,
# 	vendor_sur_id STRING,
# 	note STRING,
# 	was_approved_by_ceo BOOL,
# 	was_paid_by_accountant BOOL,
# 	was_recieve BOOL,
# 	ceo_approved_datetime TIMESTAMP,
# 	accountant_paid_datetime TIMESTAMP,
# 	recieve_datetime TIMESTAMP,
# 	etl_inserted TIMESTAMP,
# 	partition_value DATE
# ) partition by partition_value;
