name: Deploy to Google Cloud VM

on:
  push:
    tags:
      - 'v*'  # Match any tag starting with 'v', e.g., v1.0.0, v2.1.0, etc.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan 35.200.94.57 >> ~/.ssh/known_hosts

    - name: Execute deployment script via SSH
      run: |
        ssh -i ~/.ssh/id_ed25519 lamyaya88@35.200.94.57 'sudo -i && cd demo-data-warehouse && make pull && make restart'
